// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    $('.show-more-button').each((function(_this) {
      return function(index, element) {
        return $(element).on('click tap', function(event) {
          var article, excerpt_article, excerpt_div;
          $('.workshop-description').each(function() {
            return $(this).addClass('hidden');
          });
          $('.workshop-excerpt').each(function() {
            return $(this).removeClass('hidden');
          });
          $('article.workshop').each(function() {
            return $(this).removeClass('details-open');
          });
          element = $(event.target);
          excerpt_div = element.parent('div');
          excerpt_div.toggleClass('hidden');
          excerpt_article = element.closest("article");
          $(excerpt_article).addClass('details-open');
          article = "#" + excerpt_div.attr('id').replace("excerpt", "full");
          return $(article).toggleClass('hidden');
        });
      };
    })(this));
    return $('.show-less-button').each((function(_this) {
      return function(index, element) {
        return $(element).on('click tap', function(event) {
          var article, excerpt_div;
          element = $(event.target);
          article = element.closest('article');
          article.toggleClass('hidden');
          excerpt_div = "#" + article.attr('id').replace("full", "excerpt");
          $(excerpt_div).toggleClass('hidden');
          return $(excerpt_div).closest('article').removeClass('details-open');
        });
      };
    })(this));
  });

}).call(this);
